include:
  - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      job-stage: "release"
      dist-job-name: "build-fedora"

stages:
  - build
  - release

variables:
  DEPENDENCIES:
    appstream
    desktop-file-utils
    gcc
    gettext
    git
    gstreamer1-plugins-base-devel
    gtk-doc
    gtk3-devel
    itstool
    libcanberra-devel
    libnotify-devel
    libxml2-devel
    libxslt
    meson
    ninja-build
    pkgconfig(libburn-1)
    pkgconfig(libisofs-1)
    pkgconfig(tracker-sparql-3.0)
    totem-pl-parser-devel
    yelp-tools

build-fedora:
  image: fedora:latest
  stage: build
  before_script:
    - dnf install -y $DEPENDENCIES
    - git config --global --add safe.directory "$CI_PROJECT_DIR"
  script:
    - meson setup _build -Dgtk-doc=true
    - ninja -C _build
    - meson test -C _build --print-errorlogs
    - ninja -C _build install
    - meson dist -C _build
    - mkdir -p "${CI_PROJECT_DIR}/public-dist"
    - cp -a _build/meson-dist/. "${CI_PROJECT_DIR}/public-dist/"
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: "always"
    paths:
      - "public-dist"
