stages:
- build

variables:
  DEPENDENCIES:
    desktop-file-utils
    gcc
    gettext
    gstreamer1-plugins-base-devel
    gtk-doc
    gtk3-devel
    itstool
    appstream
    libcanberra-devel
    libnotify-devel
    libxml2-devel
    libxslt
    meson
    ninja-build
    pkgconfig(libburn-1)
    pkgconfig(libisofs-1)
    pkgconfig(tracker-sparql-3.0)
    totem-pl-parser-devel
    yelp-tools

build-fedora:
  image: fedora:latest
  stage: build
  before_script:
    - dnf install -y $DEPENDENCIES
  script:
    - meson setup _build -Dgtk-doc=true
    - ninja -C _build
    - meson test -C _build --print-errorlogs
    - ninja -C _build install

