inotify_sources = files('brasero-file-monitor.c')

libbrasero_burn = library(
    'brasero-burn3',
    files(
        'brasero-blank-dialog.c',
        'brasero-burn-dialog.c',
        'brasero-burn-options.c',
        'brasero-burn.c',
        'brasero-caps-burn.c',
        'brasero-caps-plugin.c',
        'brasero-caps-session.c',
        'brasero-cover.c',
        'brasero-data-project.c',
        'brasero-data-session.c',
        'brasero-data-tree-model.c',
        'brasero-data-vfs.c',
        'brasero-dest-selection.c',
        'brasero-drive-properties.c',
        'brasero-file-node.c',
        'brasero-filtered-uri.c',
        'brasero-image-properties.c',
        'brasero-image-type-chooser.c',
        'brasero-medium-properties.c',
        'brasero-progress.c',
        'brasero-session-cfg.c',
        'brasero-session-span.c',
        'brasero-session.c',
        'brasero-src-image.c',
        'brasero-src-selection.c',
        'brasero-status-dialog.c',
        'brasero-status.c',
        'brasero-sum-dialog.c',
        'brasero-tool-dialog.c',
        'brasero-track-data-cfg.c',
        'brasero-track-data.c',
        'brasero-track-disc.c',
        'brasero-track-disc.c',
        'brasero-track-image-cfg.c',
        'brasero-track-image.c',
        'brasero-track-stream-cfg.c',
        'brasero-track-stream.c',
        'brasero-track-type.c',
        'brasero-track.c',
        'brasero-video-options.c',
        'brasero-xfer.c',
        'burn-basics.c',
        'burn-caps.c',
        'burn-dbus.c',
        'burn-debug.c',
        'burn-image-format.c',
        'burn-job.c',
        'burn-mkisofs-base.c',
        'burn-plugin-manager.c',
        'burn-plugin.c',
        'burn-task-ctx.c',
        'burn-task-item.c',
        'burn-task.c',
    ),
    conf.get('BUILD_INOTIFY') ? inotify_sources : [],
    gnome.genmarshal(
        'libbrasero-marshal',
        prefix: 'brasero_marshal',
        sources: 'libbrasero-marshal.list',
    ),
    dependencies: [
        gdk3,
        gdk_x11_3,
        gio2,
        glib2,
        gmodule2,
        gobject2,
        gstreamer1,
        gstreamer_pbutils1,
        gtk3,
        libbrasero_media,
        libbrasero_utils,
        libcanberra_gtk3,
        libm,
        libnotify,
    ],
    include_directories: root_inc,
    install: true,
    version: library_version,
)

install_headers(
    files(
        'brasero-blank-dialog.h',
        'brasero-burn-dialog.h',
        'brasero-burn-options.h',
        'brasero-burn.h',
        'brasero-enums.h',
        'brasero-error.h',
        'brasero-session-cfg.h',
        'brasero-session-span.h',
        'brasero-session.h',
        'brasero-status.h',
        'brasero-sum-dialog.h',
        'brasero-tags.h',
        'brasero-tool-dialog.h',
        'brasero-track-data-cfg.h',
        'brasero-track-data.h',
        'brasero-track-disc.h',
        'brasero-track-image-cfg.h',
        'brasero-track-image.h',
        'brasero-track-stream-cfg.h',
        'brasero-track-stream.h',
        'brasero-track-type.h',
        'brasero-track.h',
    ),
    configure_file(
        configuration: conf_lib,
        input: 'brasero-burn-lib.h.in',
        output: '@BASENAME@',
    ),
    subdir: 'brasero3',
)

pkgconfig.generate(
    libbrasero_burn,
    name: 'libbrasero-burn3',
    subdirs: 'brasero3',
)

libbrasero_burn = declare_dependency(
    dependencies: libbrasero_media,
    include_directories: '.',
    link_with: libbrasero_burn,
)
meson.override_dependency('libbrasero-burn3', libbrasero_burn)
