public_icons = files(
    'hicolor_apps_16x16_brasero.png',
    'hicolor_apps_22x22_brasero.png',
    'hicolor_apps_24x24_brasero.png',
    'hicolor_apps_256x256_brasero.png',
    'hicolor_apps_32x32_brasero.png',
    'hicolor_apps_48x48_brasero.png',
    'hicolor_apps_scalable_brasero-symbolic.svg',
)

private_icons = files(
    'hicolor_actions_16x16_insert-pause.png',
    'hicolor_actions_16x16_iso-image-burn.png',
    'hicolor_actions_16x16_iso-image-new.png',
    'hicolor_actions_16x16_media-optical-audio-new.png',
    'hicolor_actions_16x16_media-optical-blank.png',
    'hicolor_actions_16x16_media-optical-burn.png',
    'hicolor_actions_16x16_media-optical-copy.png',
    'hicolor_actions_16x16_media-optical-data-new.png',
    'hicolor_actions_16x16_media-optical-video-new.png',
    'hicolor_actions_16x16_transform-crop-and-resize.png',
    'hicolor_actions_22x22_insert-pause.png',
    'hicolor_actions_22x22_iso-image-burn.png',
    'hicolor_actions_22x22_iso-image-new.png',
    'hicolor_actions_22x22_media-optical-audio-new.png',
    'hicolor_actions_22x22_media-optical-blank.png',
    'hicolor_actions_22x22_media-optical-burn.png',
    'hicolor_actions_22x22_media-optical-copy.png',
    'hicolor_actions_22x22_media-optical-data-new.png',
    'hicolor_actions_22x22_media-optical-video-new.png',
    'hicolor_actions_22x22_transform-crop-and-resize.png',
    'hicolor_actions_24x24_insert-pause.png',
    'hicolor_actions_24x24_iso-image-burn.png',
    'hicolor_actions_24x24_iso-image-new.png',
    'hicolor_actions_24x24_media-optical-audio-new.png',
    'hicolor_actions_24x24_media-optical-blank.png',
    'hicolor_actions_24x24_media-optical-burn.png',
    'hicolor_actions_24x24_media-optical-copy.png',
    'hicolor_actions_24x24_media-optical-data-new.png',
    'hicolor_actions_24x24_media-optical-video-new.png',
    'hicolor_actions_24x24_transform-crop-and-resize.png',
    'hicolor_actions_32x32_insert-pause.png',
    'hicolor_actions_32x32_iso-image-burn.png',
    'hicolor_actions_32x32_iso-image-new.png',
    'hicolor_actions_32x32_media-optical-audio-new.png',
    'hicolor_actions_32x32_media-optical-blank.png',
    'hicolor_actions_32x32_media-optical-burn.png',
    'hicolor_actions_32x32_media-optical-copy.png',
    'hicolor_actions_32x32_media-optical-data-new.png',
    'hicolor_actions_32x32_media-optical-video-new.png',
    'hicolor_actions_32x32_transform-crop-and-resize.png',
    'hicolor_actions_48x48_media-optical-video-new.png',
    'hicolor_actions_scalable_insert-pause.svg',
    'hicolor_actions_scalable_iso-image-burn.svg',
    'hicolor_actions_scalable_iso-image-new.svg',
    'hicolor_actions_scalable_media-optical-audio-new.svg',
    'hicolor_actions_scalable_media-optical-blank.svg',
    'hicolor_actions_scalable_media-optical-burn.svg',
    'hicolor_actions_scalable_media-optical-copy.svg',
    'hicolor_actions_scalable_media-optical-data-new.svg',
    'hicolor_actions_scalable_transform-crop-and-resize.svg',
    'hicolor_status_16x16_brasero-disc-00.png',
    'hicolor_status_16x16_brasero-disc-05.png',
    'hicolor_status_16x16_brasero-disc-10.png',
    'hicolor_status_16x16_brasero-disc-100.png',
    'hicolor_status_16x16_brasero-disc-15.png',
    'hicolor_status_16x16_brasero-disc-20.png',
    'hicolor_status_16x16_brasero-disc-25.png',
    'hicolor_status_16x16_brasero-disc-30.png',
    'hicolor_status_16x16_brasero-disc-35.png',
    'hicolor_status_16x16_brasero-disc-40.png',
    'hicolor_status_16x16_brasero-disc-45.png',
    'hicolor_status_16x16_brasero-disc-50.png',
    'hicolor_status_16x16_brasero-disc-55.png',
    'hicolor_status_16x16_brasero-disc-60.png',
    'hicolor_status_16x16_brasero-disc-65.png',
    'hicolor_status_16x16_brasero-disc-70.png',
    'hicolor_status_16x16_brasero-disc-75.png',
    'hicolor_status_16x16_brasero-disc-80.png',
    'hicolor_status_16x16_brasero-disc-85.png',
    'hicolor_status_16x16_brasero-disc-90.png',
    'hicolor_status_16x16_brasero-disc-95.png',
    'hicolor_status_22x22_brasero-disc-00.png',
    'hicolor_status_22x22_brasero-disc-05.png',
    'hicolor_status_22x22_brasero-disc-10.png',
    'hicolor_status_22x22_brasero-disc-100.png',
    'hicolor_status_22x22_brasero-disc-15.png',
    'hicolor_status_22x22_brasero-disc-20.png',
    'hicolor_status_22x22_brasero-disc-25.png',
    'hicolor_status_22x22_brasero-disc-30.png',
    'hicolor_status_22x22_brasero-disc-35.png',
    'hicolor_status_22x22_brasero-disc-40.png',
    'hicolor_status_22x22_brasero-disc-45.png',
    'hicolor_status_22x22_brasero-disc-50.png',
    'hicolor_status_22x22_brasero-disc-55.png',
    'hicolor_status_22x22_brasero-disc-60.png',
    'hicolor_status_22x22_brasero-disc-65.png',
    'hicolor_status_22x22_brasero-disc-70.png',
    'hicolor_status_22x22_brasero-disc-75.png',
    'hicolor_status_22x22_brasero-disc-80.png',
    'hicolor_status_22x22_brasero-disc-85.png',
    'hicolor_status_22x22_brasero-disc-90.png',
    'hicolor_status_22x22_brasero-disc-95.png',
    'hicolor_status_24x24_brasero-disc-00.png',
    'hicolor_status_24x24_brasero-disc-05.png',
    'hicolor_status_24x24_brasero-disc-10.png',
    'hicolor_status_24x24_brasero-disc-100.png',
    'hicolor_status_24x24_brasero-disc-15.png',
    'hicolor_status_24x24_brasero-disc-20.png',
    'hicolor_status_24x24_brasero-disc-25.png',
    'hicolor_status_24x24_brasero-disc-30.png',
    'hicolor_status_24x24_brasero-disc-35.png',
    'hicolor_status_24x24_brasero-disc-40.png',
    'hicolor_status_24x24_brasero-disc-45.png',
    'hicolor_status_24x24_brasero-disc-50.png',
    'hicolor_status_24x24_brasero-disc-55.png',
    'hicolor_status_24x24_brasero-disc-60.png',
    'hicolor_status_24x24_brasero-disc-65.png',
    'hicolor_status_24x24_brasero-disc-70.png',
    'hicolor_status_24x24_brasero-disc-75.png',
    'hicolor_status_24x24_brasero-disc-80.png',
    'hicolor_status_24x24_brasero-disc-85.png',
    'hicolor_status_24x24_brasero-disc-90.png',
    'hicolor_status_24x24_brasero-disc-95.png',
    'hicolor_status_32x32_brasero-disc-00.png',
    'hicolor_status_32x32_brasero-disc-05.png',
    'hicolor_status_32x32_brasero-disc-10.png',
    'hicolor_status_32x32_brasero-disc-100.png',
    'hicolor_status_32x32_brasero-disc-15.png',
    'hicolor_status_32x32_brasero-disc-20.png',
    'hicolor_status_32x32_brasero-disc-25.png',
    'hicolor_status_32x32_brasero-disc-30.png',
    'hicolor_status_32x32_brasero-disc-35.png',
    'hicolor_status_32x32_brasero-disc-40.png',
    'hicolor_status_32x32_brasero-disc-45.png',
    'hicolor_status_32x32_brasero-disc-50.png',
    'hicolor_status_32x32_brasero-disc-55.png',
    'hicolor_status_32x32_brasero-disc-60.png',
    'hicolor_status_32x32_brasero-disc-65.png',
    'hicolor_status_32x32_brasero-disc-70.png',
    'hicolor_status_32x32_brasero-disc-75.png',
    'hicolor_status_32x32_brasero-disc-80.png',
    'hicolor_status_32x32_brasero-disc-85.png',
    'hicolor_status_32x32_brasero-disc-90.png',
    'hicolor_status_32x32_brasero-disc-95.png',
    'hicolor_status_scalable_brasero-disc-00.svg',
    'hicolor_status_scalable_brasero-disc-05.svg',
    'hicolor_status_scalable_brasero-disc-10.svg',
    'hicolor_status_scalable_brasero-disc-100.svg',
    'hicolor_status_scalable_brasero-disc-15.svg',
    'hicolor_status_scalable_brasero-disc-20.svg',
    'hicolor_status_scalable_brasero-disc-25.svg',
    'hicolor_status_scalable_brasero-disc-30.svg',
    'hicolor_status_scalable_brasero-disc-35.svg',
    'hicolor_status_scalable_brasero-disc-40.svg',
    'hicolor_status_scalable_brasero-disc-45.svg',
    'hicolor_status_scalable_brasero-disc-50.svg',
    'hicolor_status_scalable_brasero-disc-55.svg',
    'hicolor_status_scalable_brasero-disc-60.svg',
    'hicolor_status_scalable_brasero-disc-65.svg',
    'hicolor_status_scalable_brasero-disc-70.svg',
    'hicolor_status_scalable_brasero-disc-75.svg',
    'hicolor_status_scalable_brasero-disc-80.svg',
    'hicolor_status_scalable_brasero-disc-85.svg',
    'hicolor_status_scalable_brasero-disc-90.svg',
    'hicolor_status_scalable_brasero-disc-95.svg',
)

foreach dest, icons : {
    datadir / 'icons': public_icons,
    # this should probably be under 'prefix/lib' instead, since it's private to brasero
    datadir / 'brasero/icons': private_icons,
}
    foreach icon : icons
        icon_path_name = fs.name(icon.full_path())
        icon_path = icon_path_name.split('_')

        if icon_path.length() != 4
            _conf = configuration_data()
            _conf.set_quoted('_', icon_path_name)
            error(
                'Unexpected amount of underscores in filename @0@'.format(
                    _conf.get('_'),
                ),
            )
        endif

        install_data(
            icon,
            install_dir: dest / icon_path[0] / icon_path[2] / icon_path[1],
            rename: icon_path[3],
        )
    endforeach
endforeach
