playlist_sources = files('brasero-playlist.c', 'brasero-search-engine.c')

preview_sources = files(
    'brasero-player-bacon.c',
    'brasero-player.c',
    'brasero-preview.c',
)

search_sources = files('brasero-search-tracker.c')

executable(
    'brasero',
    files(
        'baobab-cell-renderer-progress.c',
        'brasero-app.c',
        'brasero-audio-disc.c',
        'brasero-cli.c',
        'brasero-data-disc.c',
        'brasero-disc.c',
        'brasero-drive-settings.c',
        'brasero-eject-dialog.c',
        'brasero-file-chooser.c',
        'brasero-file-filtered.c',
        'brasero-filter-option.c',
        'brasero-layout-object.c',
        'brasero-layout.c',
        'brasero-multi-dnd.c',
        'brasero-multi-song-props.c',
        'brasero-plugin-manager-ui.c',
        'brasero-plugin-option.c',
        'brasero-pref.c',
        'brasero-project-manager.c',
        'brasero-project-name.c',
        'brasero-project-parse.c',
        'brasero-project-type-chooser.c',
        'brasero-project.c',
        'brasero-rename.c',
        'brasero-setting.c',
        'brasero-song-control.c',
        'brasero-song-properties.c',
        'brasero-split-dialog.c',
        'brasero-time-button.c',
        'brasero-uri-container.c',
        'brasero-utils.c',
        'brasero-video-disc.c',
        'brasero-video-tree-model.c',
        'eggtreemultidnd.c',
        'main.c',
    ),
    gstreamer_video1.found() ? preview_sources : [],
    totem_plparser.found() ? playlist_sources : [],
    tracker_sparql3.found() ? search_sources : [],
    dependencies: [
        cairo,
        gdk3,
        gdk_x11_3,
        gio2,
        glib2,
        gobject2,
        gstreamer1,
        gstreamer_video1.found() ? gstreamer_video1 : [],
        gthread2,
        gtk3,
        libbrasero_burn,
        libbrasero_media,
        libbrasero_utils,
        libxml2,
        totem_plparser.found() ? totem_plparser : [],
        tracker_sparql3.found() ? tracker_sparql3 : [],
    ],
    include_directories: root_inc,
    install: true,
)
