version_xml = configure_file(
    input: 'version.xml.in',
    output: 'version.xml',
    configuration: conf,
)

ignore_headers = [
    'brasero-gio-operation.h',
    'brasero-media-private.h',
    'brasero-medium-selection-priv.h',
    'burn-iso-field.h',
    'burn-iso9660.h',
    'burn-susp.h',
    'burn-volume-source.h',
    'burn-volume.h',
    'libbrasero-marshal.h',
    'scsi-base.h',
    'scsi-command.h',
    'scsi-device.h',
    'scsi-dvd-structures.h',
    'scsi-error.h',
    'scsi-get-configuration.h',
    'scsi-get-performance.h',
    'scsi-inquiry.h',
    'scsi-mech-status.h',
    'scsi-mmc1.h',
    'scsi-mmc2.h',
    'scsi-mmc3.h',
    'scsi-mode-pages.h',
    'scsi-opcodes.h',
    'scsi-q-subchannel.h',
    'scsi-read-capacity.h',
    'scsi-read-cd.h',
    'scsi-read-disc-info.h',
    'scsi-read-disc-structure.h',
    'scsi-read-format-capacities.h',
    'scsi-read-toc-pma-atip.h',
    'scsi-read-track-information.h',
    'scsi-sbc.h',
    'scsi-sense-data.h',
    'scsi-spc1.h',
    'scsi-status-page.h',
    'scsi-utils.h',
    'scsi-write-page.h',
]

gnome.gtkdoc(
    'libbrasero-media',
    content_files: [version_xml],
    dependencies: libbrasero_media,
    ignore_headers: ignore_headers,
    install: true,
    main_sgml: 'libbrasero-media-docs.sgml',
    mkdb_args: ['--sgml-mode', '--output-format=xml'],
    scan_args: ['--rebuild-types'],
    src_dir: [
        meson.project_source_root() / 'libbrasero-media',
        meson.project_build_root() / 'libbrasero-media',
    ],
)
