version_xml = configure_file(
    input: 'version.xml.in',
    output: 'version.xml',
    configuration: conf,
)

ignore_headers = [
    'brasero-caps-burn.h',
    'brasero-cover.h',
    'brasero-data-project.h',
    'brasero-data-session.h',
    'brasero-data-tree-model.h',
    'brasero-data-vfs.h',
    'brasero-dest-selection.h',
    'brasero-drive-properties.h',
    'brasero-file-monitor.h',
    'brasero-file-node.h',
    'brasero-filtered-uri.h',
    'brasero-image-properties.h',
    'brasero-image-type-chooser.h',
    'brasero-medium-properties.h',
    'brasero-plugin-information.h',
    'brasero-plugin-registration.h',
    'brasero-plugin.h',
    'brasero-progress.h',
    'brasero-session-helper.h',
    'brasero-src-image.h',
    'brasero-src-selection.h',
    'brasero-status-dialog.h',
    'brasero-tool-dialog-private.h',
    'brasero-track-type-private.h',
    'brasero-tray.h',
    'brasero-video-options.h',
    'brasero-xfer.h',
    'burn-basics.h',
    'burn-caps.h',
    'burn-dbus.h',
    'burn-debug.h',
    'burn-image-format.h',
    'burn-job.h',
    'burn-mkisofs-base.h',
    'burn-plugin-manager.h',
    'burn-process.h',
    'burn-task-ctx.h',
    'burn-task-item.h',
    'burn-task.h',
    'libbrasero-marshal.h',
]

gnome.gtkdoc(
    'libbrasero-burn',
    content_files: [version_xml],
    dependencies: libbrasero_burn,
    ignore_headers: ignore_headers,
    install: true,
    main_sgml: 'libbrasero-burn-docs.sgml',
    mkdb_args: ['--sgml-mode', '--output-format=xml'],
    scan_args: ['--rebuild-types'],
    src_dir: [
        meson.project_source_root() / 'libbrasero-burn',
        meson.project_build_root() / 'libbrasero-burn',
    ],
)
